# Generated by Django 2.2.3 on 2019-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_mohth',
            new_name='birth_month',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birth_yaer',
            new_name='birth_year',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.IntegerField(choices=[(0, '全部'), (1, '男'), (2, '女')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海'), ('gz', '广州'), ('cd', '成都'), ('dl', '大连')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海'), ('gz', '广州'), ('cd', '成都'), ('dl', '大连')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '全部'), (1, '男'), (2, '女')], default=0),
        ),
    ]
